apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector: 
    app: kubeuser
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kubeuser
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeuser
  template:
    metadata:
      labels:
        app: kubeuser
    spec:
      containers:
      - name: kubecontainer
        image: coffeyor/dockeroperations:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: mongodb+srv://Coffeyorky:thebadbatch123@cluster0.j69jxej.mongodb.net/ecommerce?retryWrites=true&w=majority
        imagePullPolicy: Always
